#!/usr/bin/env python3
"""Generate sw-cache.js — a precache manifest of all local assets for offline PWA."""
from __future__ import annotations
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "sw-cache.js"

EXTENSIONS = {".js", ".css", ".svg", ".json", ".html", ".png", ".ico"}
IGNORE_DIRS = {".git", ".vercel", "landing", "scripts", "node_modules"}


def find_local_assets() -> list[str]:
    urls = set()
    for path in ROOT.rglob("*"):
        if path.is_dir():
            continue
        if any(d in path.parts for d in IGNORE_DIRS):
            continue
        if path.suffix not in EXTENSIONS:
            continue
        rel = "/" + str(path.relative_to(ROOT))
        urls.add(rel)
    # Always include root
    urls.add("/")
    return sorted(urls)


def main() -> None:
    urls = find_local_assets()
    lines = [
        "// AUTO-GENERATED by scripts/gen-sw-cache.py — do not edit",
        f"const PP_PRECACHE_URLS = {urls};",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {OUT} with {len(urls)} URLs")


if __name__ == "__main__":
    main()
